[theme]
primaryColor = "#00ff7f"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#f0f2f6"
font = "sans serif"

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false

